default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres4dm1n
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: registration_development

test:
  <<: *default
  database: registration_test

production:
  <<: *default
  database: registration_production
